// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pizzmspeqevaizybssie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpenptc3BlcWV2YWl6eWJzc2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTAxOTMsImV4cCI6MjA3MTg4NjE5M30.hBFmtNRig7XOtbsJoIq1ZiSzOVp362HkqPHA0gOF0Bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});